### ISSUE TITLE
Let's encrypt client is now called certbot

### ISSUE THREAD

**Issue by heygrady** [llambiel/letsecureme#16]
Your docs [recommend installing the old let's encrypt client](https://github.com/llambiel/letsecureme/blob/master/content/2016-03-15-lets-encrypt-and-nginx-state-of-the-art-of-a-secure-web-deployment.md#lets-encrypt-setup-ssl-certificates-and-nginx-https-config) -- which is probably wrong.

Your docs are great but they are drifting out of date. In May of 2016, the [EFF superseded the `letsencrypt` cleint with `certbot`](https://www.eff.org/deeplinks/2016/05/announcing-certbot-new-tls-robot).

[Digital Ocean has a similar docs](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) to yours. They demonstrate using `certbot`

```bash
# see the digital ocean docs for details
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot
sudo certbot certonly --webroot --webroot-path=/var/www/html -d example.com -d www.example.com
```

**Comment by llambiel** [comment]
Updated thru https://github.com/llambiel/letsecureme/pull/17

Thanks for the heads up
