### ISSUE TITLE
How to point subdomain to gh-page?

### ISSUE THREAD

**Issue by katopz** [llambiel/letsecureme#4]
Hi,

Thanks for super awesome guide. Everything work just fine.
BTW When I try to setup subdomain and point to gh-page, it seem to have a problem with SSL.

![screen shot 2559-04-09 at 19 40 33](https://cloud.githubusercontent.com/assets/97060/14403666/fcea29c4-fe8a-11e5-9e6a-6af521411fd1.png)

![screen shot 2559-04-09 at 19 56 19](https://cloud.githubusercontent.com/assets/97060/14403747/55cc0f6a-fe8d-11e5-8099-b0c6fe7bb686.png)

```
$ORIGIN rabbot.io.
$TTL 1800
rabbot.io. IN SOA ns1.digitalocean.com. hostmaster.rabbot.io. 1460204090 10800 3600 604800 1800
rabbot.io. 1800 IN NS ns1.digitalocean.com.
rabbot.io. 1800 IN NS ns2.digitalocean.com.
rabbot.io. 1800 IN NS ns3.digitalocean.com.
rabbot.io. 1800 IN A 128.199.210.13
www.rabbot.io. 1800 IN CNAME rabbot.io.
blog.rabbot.io. 1800 IN CNAME rabbots.github.io.
```

```
$ dig blog.rabbot.io +nostats +nocomments +nocmd

; <<>> DiG 9.8.3-P1 <<>> blog.rabbot.io +nostats +nocomments +nocmd
;; global options: +cmd
;blog.rabbot.io.            IN  A
blog.rabbot.io.     1799    IN  CNAME   rabbots.github.io.
rabbots.github.io.  3599    IN  CNAME   github.map.fastly.net.
github.map.fastly.net.  9   IN  A   103.245.222.133
```

I'm not sure what I miss. Any hint? Thanks

**Comment by llambiel** [comment]
GH pages does not support custom domains over SSL. You may use Cloudflare to achieve that but it will not be end to end encryption.

If your goal is to get your root website secured with SSL but not your subdomains, then you'll need to remove the "includeSubDomains" stanza from the HSTS header https://github.com/llambiel/letsecureme/blob/master/etc/nginx/conf.d/default.conf#L11

**Comment by katopz** [comment]
Thanks @llambiel I think I'll end up with Cloudflare. BTW that's mean this [Method A here](https://blog.kloudsec.com/how-to-setup-github-custom-domain-with-https/) is also not possible am I right? 

I did try it but it I'm not sure it work or not due to long time waiting DNS to apply it result and I think I mess thing up already here.

**Comment by llambiel** [comment]
The method A described in the article should work. Again you won't have end to end encryption.
