### ISSUE TITLE
Add server_tokens = off

### ISSUE THREAD

**Issue by dandv** [llambiel/letsecureme#5]
Helps hide the nginx version: https://scotthelme.co.uk/hardening-your-http-response-headers/#server

**Comment by llambiel** [comment]
Thanks for your suggestion.

I don't see much the added value of hiding the server version vs the drawback. Nginx provides only the version, nothing from the additional components, like Apache does (ex php version, patches etc..). So from a security perspective, this information may only be used for for 0day attacks or so, on Nginx only. 

I personally prefer having this information available, it allows power user to see that the software used is up to date (or not). From a management / monitoring / auditing & debugging perspective, having this information without logging into the machine may be helpful as well.

I agree however that server_tokens must configured accordingly on Apache as it could leak sensitive information.
