### ISSUE TITLE
404

### ISSUE THREAD

**Issue by katopz** [llambiel/letsecureme#6]
refer to https://github.com/llambiel/letsecureme/blob/master/content%2F2016-03-15-lets-encrypt-and-nginx-state-of-the-art-of-a-secure-web-deployment.md at last link which link to https://raw.githubusercontent.com/llambiel/letsecureme/ somehow appear 404 on me.

**Comment by llambiel** [comment]
Good catch, thanks ! fixed in 41cf51aef2771605047f9152b5b834ea1d22e761
