### ISSUE TITLE
Add more subdomain process?

### ISSUE THREAD

**Issue by katopz** [llambiel/letsecureme#7]
I already did add SSL for my main domain though whole process.
And now I need to request subdomain but I'm not sure where to hook in or maybe I need to redo whole process all over again?

And also let's encrypt (now [certbot](https://github.com/certbot/certbot)?) offer this...

```
./certbot-auto certonly --standalone --email admin@example.com -d example.com -d www.example.com -d other.example.net
```

So I'm even more confuse which one should I use now?
It will override or revoke old certificate or not?
Any advise the right way to do this is welcome.

Thanks.

**Comment by llambiel** [comment]
If your vhost handle multiple domains, just redo the process with all your domains in the list:

sudo letsencrypt certonly -a webroot --webroot-path=/your/path -d example.com -d www.example.com -d other.example.net 

This will replace the old certificate with a new one including all your specified domains.

Hope that helps
