### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by rugk** [llambiel/letsecureme#8]
1. LE is not [in beta anymore](https://letsencrypt.org//2016/04/12/leaving-beta-new-sponsors.html).
2. The LE client is n ow called [certbot](https://certbot.eff.org/).

**Comment by llambiel** [comment]
Thanks for your input.

This article has been posted in March and, as you noted, a few part are no longer accurate. I'm planning to do a refresh within 1 or 2 weeks, which will also be based on the new Ubuntu 16.04 OS.

**Comment by llambiel** [comment]
Fixed with https://github.com/llambiel/letsecureme/pull/9/
